#!/bin/bash
#SBATCH --account=uppmax2025-2-337 # Project account
#SBATCH --ntasks=1                    # Number of cores
#SBATCH --time=24:00:00               # Time limit (hh:mm:ss)

# Check if we have the right number of arguments
if [[ $# -ne 3 ]]; then
    echo "Incorrect # of arguments passed to this script! See below:"
    echo "Usage: $0 <configuration> <results_dir> <full_trace_path>"
    echo "Configurations:"
    echo "  cxl_only                : CXL memory system"
    echo "  dram_only               : Local DRAM memory system"
    echo "  interleaving            : Tiered memory with interleaving allocation, ratio 1:1"
    echo "  access_r1_1             : Access-count-based heatmap, ratio 1:1"
    echo "  access_r1_3             : Access-count-based heatmap, ratio 1:3 (default)"
    echo "  criticality_r1_1        : Criticality-based heatmap, ratio 1:1"
    echo "  criticality_r1_3        : Criticality-based heatmap, ratio 1:3 (default)"
    exit 1
fi

# Extract arguments
CONFIGURATION="$1"
RESULTS_DIR="$2"
FULL_TRACE_PATH="$3"

# Base parameters
WARMUP_INSTRUCTIONS=50000000
SIMULATION_INSTRUCTIONS=100000000
ARGS="-w $WARMUP_INSTRUCTIONS -i $SIMULATION_INSTRUCTIONS"

# Project base directory
CHAMPSIM_BASE="/proj/uart_chp_cxl_trans/songtao/ChampSim-dev"

# Binary paths
DRAM_BINARY="$CHAMPSIM_BASE/bin/champsim_dram_only"
TIERED_BINARY="$CHAMPSIM_BASE/bin/champsim_tiered_memory"
CXL_BINARY="$CHAMPSIM_BASE/bin/champsim_cxl_only"

# Heatmap file path with trace name for identification
HEATMAP_DIR="$RESULTS_DIR/heatmaps"
TRACE_NAME=$(basename "$FULL_TRACE_PATH" .xz)

# Configure based on the configuration argument
case "$CONFIGURATION" in
    "cxl_only")
        CONFIG_TYPE="single"
        COMMAND="$CXL_BINARY $ARGS $FULL_TRACE_PATH"
        ;;
    "dram_only")
        CONFIG_TYPE="single"
        COMMAND="$DRAM_BINARY $ARGS $FULL_TRACE_PATH"
        ;;
    "interleaving")
        CONFIG_TYPE="single"
        COMMAND="$TIERED_BINARY $ARGS $FULL_TRACE_PATH"
        ;;
    "access_r1_1")
        CONFIG_TYPE="heatmap"
        HEATMAP_TYPE="access"
        RATIO="1:1"
        RATIO_STR="r1_1"
        SORT_FLAG=""
        ;;
    "access_r1_3")
        CONFIG_TYPE="heatmap"
        HEATMAP_TYPE="access"
        RATIO="1:3"
        RATIO_STR="r1_3"
        SORT_FLAG=""
        ;;
    "criticality_r1_1")
        CONFIG_TYPE="heatmap"
        HEATMAP_TYPE="criticality"
        RATIO="1:1"
        RATIO_STR="r1_1"
        SORT_FLAG="--sort-by-criticality"
        ;;
    "criticality_r1_3")
        CONFIG_TYPE="heatmap"
        HEATMAP_TYPE="criticality"
        RATIO="1:3"
        RATIO_STR="r1_3"
        SORT_FLAG="--sort-by-criticality"
        ;;
    *)
        echo "Invalid configuration: $CONFIGURATION"
        echo "Valid configurations: cxl_only, dram_only, interleaving, access_r1_1, access_r1_3, criticality_r1_1, criticality_r1_3"
        exit 1
        ;;
esac

# Execute based on configuration type
if [ "$CONFIG_TYPE" = "heatmap" ]; then
    # Two-phase execution for heatmap-based allocation
    HEATMAP_FILE="$HEATMAP_DIR/${TRACE_NAME}_${HEATMAP_TYPE}_${RATIO_STR}"

    # Clean old heatmap data
    echo "=== Cleaning old heatmap data ==="
    rm "$HEATMAP_FILE" 2>/dev/null
    touch "$HEATMAP_FILE"

    # Phase 1: Generate heatmap
    echo "=== PHASE 1: Generating heatmap ==="
    GENERATE_COMMAND="$DRAM_BINARY $ARGS --generate-heatmap $HEATMAP_FILE $FULL_TRACE_PATH"
    echo "Executing: $GENERATE_COMMAND"
    $GENERATE_COMMAND

    if [ $? -ne 0 ]; then
        echo "ERROR: Heatmap generation failed!"
        exit 1
    fi

    # Phase 2: Use heatmap for simulation
    echo "=== PHASE 2: Using heatmap for simulation ($HEATMAP_TYPE based, ratio $RATIO) ==="
    COMMAND="$TIERED_BINARY $ARGS --use-heatmap $HEATMAP_FILE $SORT_FLAG --ratio $RATIO $FULL_TRACE_PATH"
fi

# Run the final command
echo "Executing: $COMMAND"
$COMMAND 2>&1
# There is no conflict between '2>&1' and f'--error={outputdir}/{conf_prefix}.err'
# in runall_pelle.py because all .err file would only contain err info generated by
# Slurm, and .out file would contain both stdout and stderr msg from running traces 
