#!/bin/bash
#SBATCH --account=uppmax2025-2-337 # Project account
#SBATCH --ntasks=1                    # Number of cores
#SBATCH --time=12:00:00               # Time limit (hh:mm:ss)

# Check if we have the right number of arguments
if [[ $# -ne 3 ]]; then
    echo "Incorrect # of arguments passed to this script! See below:"
    echo "Usage: $0 <configuration> <results_dir> <full_trace_path>"
    echo "Configurations:"
    echo "  cxl_only                   : CXL-only memory system"
    echo "  dram_only                  : DRAM-only memory system"
    echo "  hybrid-roundrobin          : Hybrid with round-robin allocation"
    echo "  hybrid-hotness-access      : Hybrid with access-count-based heatmap"
    echo "  hybrid-hotness-criticality : Hybrid with criticality-based heatmap"
    exit 1
fi

# Extract arguments
CONFIGURATION="$1"
RESULTS_DIR="$2"
FULL_TRACE_PATH="$3"

# Base parameters
WARMUP_INSTRUCTIONS=50000000
SIMULATION_INSTRUCTIONS=100000000
ARGS="-w $WARMUP_INSTRUCTIONS -i $SIMULATION_INSTRUCTIONS"

# Project base directory
CHAMPSIM_BASE="/proj/uart_chp_cxl_trans/songtao/ChampSim-dev"

# Heatmap file path with trace name for identification
HEATMAP_DIR="$RESULTS_DIR/heatmaps"
TRACE_NAME=$(basename "$FULL_TRACE_PATH" .xz)

# Configure based on the configuration argument
case "$CONFIGURATION" in
    "cxl_only")
        BINARY="$CHAMPSIM_BASE/bin/champsim_cxl_only"
        COMMAND="$BINARY $ARGS $FULL_TRACE_PATH"
        ;;
    "dram_only")
        BINARY="$CHAMPSIM_BASE/bin/champsim_dram_only"
        COMMAND="$BINARY $ARGS $FULL_TRACE_PATH"
        ;;
    "hybrid-roundrobin")
        BINARY="$CHAMPSIM_BASE/bin/champsim_hybrid"
        COMMAND="$BINARY $ARGS $FULL_TRACE_PATH"
        ;;
    "hybrid-hotness-access")
        # Two-phase execution for access-count-based heatmap allocation
        BINARY="$CHAMPSIM_BASE/bin/champsim_hybrid"
        HEATMAP_FILE="$HEATMAP_DIR/${TRACE_NAME}_access"

        echo "=== PHASE 1: Generating heatmap ==="
        GENERATE_COMMAND="$BINARY $ARGS --generate-heatmap $HEATMAP_FILE $FULL_TRACE_PATH"
        echo "Executing: $GENERATE_COMMAND"
        $GENERATE_COMMAND

        if [ $? -ne 0 ]; then
            echo "ERROR: Heatmap generation failed!"
            exit 1
        fi

        echo "=== PHASE 2: Using heatmap for simulation (access-count based) ==="
        COMMAND="$BINARY $ARGS --use-heatmap $HEATMAP_FILE $FULL_TRACE_PATH"
        ;;
    "hybrid-hotness-criticality")
        # Two-phase execution for criticality-based heatmap allocation
        BINARY="$CHAMPSIM_BASE/bin/champsim_hybrid"
        HEATMAP_FILE="$HEATMAP_DIR/${TRACE_NAME}_criticality"

        echo "=== PHASE 1: Generating heatmap ==="
        GENERATE_COMMAND="$BINARY $ARGS --generate-heatmap $HEATMAP_FILE $FULL_TRACE_PATH"
        echo "Executing: $GENERATE_COMMAND"
        $GENERATE_COMMAND

        if [ $? -ne 0 ]; then
            echo "ERROR: Heatmap generation failed!"
            exit 1
        fi

        echo "=== PHASE 2: Using heatmap for simulation (criticality based) ==="
        COMMAND="$BINARY $ARGS --use-heatmap $HEATMAP_FILE --sort-by-criticality $FULL_TRACE_PATH"
        ;;
    *)
        echo "Invalid configuration: $CONFIGURATION"
        echo "Valid configurations: cxl_only, dram_only, hybrid-roundrobin, hybrid-hotness-access, hybrid-hotness-criticality"
        exit 1
        ;;
esac

# Run the final command
echo "Executing: $COMMAND"
$COMMAND 2>&1
# There is no conflict between '2>&1' and f'--error={outputdir}/{conf_prefix}.err'
# in runall_pelle.py because all .err file would only contain err info generated by
# Slurm, and .out file would contain both stdout and stderr msg from running traces 
